### ISSUE TITLE
Proposing change in database structure

### ISSUE THREAD

**Issue by FaiyazMujawar** [Zeal-Student-Developers/issue-tracker#39]
Currently, the schema for Issues is:
```
{
  Name
  Description
  Comments:[]
  Solutions:[]
  <Rest of the details>
}
```

This schema may be sufficient for small number of comments/solutions. If the number increases, the size of single document in the memory increases, which in worse case may exceed the limit for a document in mongodb. Also, when accessing an issue, the comments and solutions are also passed, increasing the bandwidth utilisation.

What I suggest is creating a seperate collection for solutions and comments. Both can contain the id of the issue they are related to. Each document in the collection would only contain the issue id and the comment/solution contents only. In this way, comments and solutions may be accessed on demand, decreasing both the document size and bandwidth utilisation.

**Comment by drigio** [comment]
This can be a good suggestion in terms of db design. However this one to many relationship can actually be thought of as a `one to few` relationship in our case. There wont be huge amounts of comments. Also i think the document size limit is 16 MB. 16 MB of text data is a very huge size. I dont think it will affect us. 

Also if we do separate collections, then there will be an additional overload on aggregation operations. Also then we will have to manually work on consistency of data after editing. We can retrieve nested documents by limiting them so that we dont overload the api and when we need all the comments and solutions we can explicitly request for them. What do you think?
 
For reference 1 MB of unicode text contains approx 171,000 words.

**Comment by FaiyazMujawar** [comment]
Okay. It was just a suggestion

**Comment by FaiyazMujawar** [comment]
Okay. I suggested with the thought of making the design scalable. Sure at our scale it won't affect much. However, this could be an issue when the app is scaled.

**Comment by drigio** [comment]
Lets close this if it is not needed anymore @FaiyazMujawar

**Comment by FaiyazMujawar** [comment]
Yes. This can be closed.
