### ISSUE TITLE
Implement a module for posting images along with an issue.

### ISSUE THREAD

**Issue by drigio** [Zeal-Student-Developers/issue-tracker#51]
We can discuss the constraints for the same here, For ex : the max size of file, file ext, or the max number of images allowed. 

Basic idea would be 
1. to have a nodejs static image server, which only allows access to our mobile and web clients (we can add this later, just a few lines of code)
2. Hashing the `name of image and date` and storing this uniquely in the mongoDB as the filename
3. Using this filename and storing this on a folder in `localstorage` (we can later even shift to a web based file storage for scaling if needed, but mostly won't need to).
4. Sending in the `url` to the image resource in `json` back to the clients that are requesting it and, then the client will try to download and/or access the image(s) from that url.

**Comment by FaiyazMujawar** [comment]
I found a way to store the images on local storage. Files cannot be sent to the API in the JSON object. In order to send files, the encoding type must be `multipart/form-data`. Express.js by itself cannot parse `multipart/form-data`. This can be done using [Multer](https://www.npmjs.com/package/multer). However, multer stores the file directly to local storage. It cannot send a request to store the file on remote server.

**Comment by FaiyazMujawar** [comment]
I've found a way to save image on a file server.
The steps are:
- Install [multer](https://www.npmjs.com/package/multer) on main server.
- The request must be sent in  `multipart/form-data` format.
- Create a multer object with all the configurations and pass it as a middleware to the express route.

This saves the image locally in the form to the specified location. To save the image on  file server:

- Create seperate express server for file.
- Install `multer` on the file server.
- Install [form-data](https://www.npmjs.com/package/form-data) on the main server. The file must be sent in `multipart/form-data` format to the file server. However, Nodejs does not support `multipart/form-data` by default. `form-data` package takes care of it. The request can be sent by installing [axios](https://www.npmjs.com/package/axios) on the main server.
- Create a `FormData` object and send a `POST` request to the file server with the file stored locally on the main server.
- The image can be saved on the file server in the same manner as stated above for the main server.
- After saving the image on the file server, the locally saved image can be deleted.

This saves the image on the file server. However, this seems to be quite tedious for a relatively simple work. I think storing files locally may be a more feasible solution.

**Comment by drigio** [comment]
> However, this seems to be quite tedious for a relatively simple work. I think storing files locally may be a more feasible solution.

Yes I think this is becoming tedious. We needn't store the image two times, as it will consume bandwidth twice. You can watch a few videos for the same. It is relatively quite easy to do. If I find the video, ill reference it here in the comments.

**Comment by FaiyazMujawar** [comment]
Yes. I tried finding it but I could not find anything related to our case. This is the only solution I could come up with. Any help would be appreciated. But please be quick, as I may start working on this PR soon.

**Comment by drigio** [comment]
Check this link https://github.com/dharijanto/multer-proxy-storage
Edit : https://github.com/JohnKimDev/multer-proxy-storage-engine Check this, its more recent and is a fork of the one above

**Comment by FaiyazMujawar** [comment]
As per our discussion, I've drawn out the following plan:

- The client first sends a `POST` request on `api/issues/images` with media file(s) in `multipart/form-data` format.
- The main server sends the file(s) to the file server using the discussed npm package.
- The file server returns a list of paths to the saved images to the main server.
- The main server saves the recieved image path(s) into database with all the required data, like userId, issueId etc.
- The path(s) to the client.
- The client then sends another `POST` request on `api/issues/` the other issue details with returned paths in `application/json` format as follows:
  ```JSON
  {
    "title": "title",
    "description": "description",
    "images": "[List of returned paths]",
    ...any other details
  }
  ```
- The main server then stores the issue in the database. The issueId of all the images in the database is updated.

With the above plan, I have the following questions:

- How many images are allowed to be stored for each issue? Because if more than one, code changes.
- What would be schema for storing the image paths in the database?
- Where do I store the file server code? Should I create a seperate repository for the same?

**Comment by drigio** [comment]
1. I guess 3-4 should suffice.
2. What do you mean by schema for file paths? It will be simple 'directly accessible http urls'. What more schema are you thinking of?
3.  Yes a separate repo for the file server would be needed. Please go ahead and create one.

**Comment by FaiyazMujawar** [comment]
You said we're gonna save image information like userid for logging pupose. So for that, schema?
